export const ERR_MS = {
  MS1: 'Please write the Coupon Details Name within 20 characters..	쿠폰명세명은 20자이내로 작성해주세요.',
  MS2: 'This field is required.',
  MS3: 'Precision cannot be set above 100.	정율은 100 이상 설정할 수 없습니다.',
  MS4: 'Precision must be set to 0 or greater.	정율은 0 이상 설정이 되어야 합니다.',
  MS5: '최대할인금액을 입력해주세요.',
  MS6: 'Flat rate cannot be set above 1,000,000.	정액은 1,000,000 이상 설정할 수 없습니다.',
  MS7: 'Flat rate should be set to 0 or higher.	정액은 0 이상 설정이 되어야 합니다.',
  MS8: 'Minimum order amount cannot exceed KRW 1,000,000.	최소주문금액은 1,000,000원 이상 설정할 수 없습니다.',
  MS9: 'A date earlier than the start date.	시작일보다 빠른 날짜 입니다.',
  MS10: 'A date later than the end date.	종료일보다 늦은 날짜 입니다.',
  MS11: 'It is earlier than the start time.	시작시간보다 빠른 시간 입니다.',
  MS12: 'It is later than the end time.	종료시간보다 늦은 시간 입니다.',
  MS13: 'It is equals than the start time.	',
  MS14: 'Please enter N days after Issued.	발급후 N일을 입력해주세요.',
  MS15: 'Please enter the number of first-come-first-served uses.	선착순 사용 개수를 입력해주세요.',
  MS16: 'Save is required to issue coupons. Do you want to save coupon issuance? yes / no	쿠폰발행을 저장이 필요합니다. 쿠폰발행을 저장 하시겠습니까? 예 / 아니요',
  MS17: 'Do you want to save coupon issuance and specifications? yes / no	쿠폰발행 및 명세를 저장 하시겠습니까? 예 / 아니요',
  MS18: 'Are you sure you want to cancel the coupon issuance creation? yes / no	쿠폰발행생성을 취소 하시겠습니까? 예 / 아니요',
  MS19: 'Please write the coupon name within 20 characters..	쿠폰명은 20자이내로 작성해주세요.',
  MS20: 'A date earlier than the start date..	시작일보다 빠른 날짜입니다.',
  MS21: 'A date earlier than the end date..	종료일보다 늦은 날짜입니다.',
  MS22: 'Do you want to download the selected coupon details? Yes/ No	선택하신 쿠폰명세를 다운로드 하시겠습니까? 예 / 아니오',
  MS23: 'Do you want to download All Coupon Details? Yes/ No	쿠폰명세 전체를 다운로드 하시겠습니까? 예 / 아니오',
  MS24: 'Are you sure want to copy the selected coupon details? Yes/ No	선택하신 쿠폰명세를 복사하시겠습니까? 예 / 아니오',
  MS25: '1번에 1개의 쿠폰명세만 복사 가능합니다.',
  MS26: '복사하실 쿠폰명세를 선택해주세요.',
  MS27: 'Are you sure want to delete the selected coupon details? Yes / No	선택하신 쿠폰명세를 삭제하시겠습니까? 에 / 아니오',
  MS28: 'Please select coupon detail will delete	삭제할 쿠폰명세를 선택하세요.',
  MS29: 'The selected coupon details cannot be deleted. Cannot be deleted if it is not in Waiting State.	선택하신 쿠폰명세는 삭제가 불가능합니다. 대기상태가 아닌경우 삭제할 수 없습니다.',
  MS30: 'Please write the coupon name within 20 characters..	쿠폰명은 20자이내로 작성해주세요.',
  MS31: 'A date earlier than the start date.	시작일보다 빠른 날짜 입니다.',
  MS32: 'A date later than the end date.	종료일보다 늦은 날짜 입니다.',
  MS33: 'It is earlier than the start time.	시작시간보다 빠른 시간 입니다.',
  MS34: 'It is later than the end time.	종료시간보다 늦은 시간 입니다.',
  MS35: 'The same member has already been selected.	이미 동일한 회원이 선택되었습니다.',
  MS36: 'Keyword cannot be longer than 10 characters..	키워드는 10자 이상 입력할 수 없습니다.',
  MS37: 'The number of random code Issued cannot exceed 1000000.	난수코드 발급 개수는 1000000건을 초과 할 수 없습니다.',
  MS38: 'Do you want to download the selected coupon issuance details? Yes/ No	선택하신 쿠폰발급내역을 다운로드 하시겠습니까? 예 / 아니오',
  MS39: 'Do you want to download the entire coupon issuance history? Yes/ No	쿠폰발급내역 전체를 다운로드 하시겠습니까? 예 / 아니오',
  MS40: 'Do you want to copy the selected coupon issuance? Yes /No	선택하신 쿠폰발급을 복사하시겠습니까? 예 / 아니오',
  MS41: '1번에 1개의 쿠폰명세만 복사 가능합니다.',
  MS42: '복사하실 쿠폰명세를 선택해주세요.',
  MS43: 'Are you sure you want to delete the selected coupon issuance? Yes /No	선택하신 쿠폰발급을 삭제하시겠습니까? 에 / 아니오',
  MS44: 'Please select the coupon issue you want to delete.	삭제할 쿠폰발급를 선택하세요.',
  MS45: 'The selected coupon issue cannot be deleted. It cannot be deleted if it is not in Waiting mode.	선택하신 쿠폰발급은 삭제가 불가능합니다. 대기상태가 아닌경우 삭제할 수 없습니다.',
};
